In [2]:
import numpy as np
import time         # check operation time
import random       # generate random  numbers
from sys import getsizeof # check the size of objects
import math

# Performance on matrix multiplication

In [8]:
A = np.array([
    [2, 4, 1 ],
    [7, 2, 5 ]
])

B = np.array([
    [4, 5, 2],
    [6, 8, 5],
    [2, 2, 1]
])

result = A @ B   # or A @ B, np.matmul(A, B)

print(result)

[[34 44 25]
 [50 61 29]]


# Vectorized operation

In [10]:
arr1 = np.array([3, 2, 7, 9, 0])
arr2 = np.array([4, 1, 6, 8, 4])

result = arr1 * arr2  # vectorized operation

print(result)

[12  2 42 72  0]


# A simple NN

In [12]:
x = np.array([1, 2, 3])
w = np.array([0.2, 0.8, -0.5])
b = 2

z = w @ x  +  b
print(z)

2.3


In [14]:
# Activation function

output =  np.maximum(0, z)
print(output)

2.3


# Multiple Neuron Layer

In [16]:
# Input (3 features)
x = np.array([1.0, 2.0, 3.0])

# 3 neurons → each has 3 weights
W = np.array([
    [0.20, 0.80, -0.50],
    [0.50, -0.91, 0.26],
    [-0.26, -0.27, 0.17]
])

# Bias for each neuron
b = np.array([2, 3, 0.5])

# Layer output
Z = W @ x  +  b

print("Layer Output:\n", Z)

Layer Output:
 [2.3  2.46 0.21]


# Batch Input

In [17]:
# 2 samples
X = np.array([
    [1, 2, 3],
    [2, 5, -1]
])

Z = X @ (W.T)  +  b
print(Z)

[[ 2.3   2.46  0.21]
 [ 6.9  -0.81 -1.54]]


# Mini Assignment

Build this:

Input:
```
X = [[1,2,3], [4,5,6]]
```

## Task:

Create:
- 4 neurons
- random weights
- random bias
- Output final matrix

In [18]:
# Solution
import numpy as np

# Input (2 samples, 3 features)
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Step 1: Initialize random weights (4 neurons, 3 inputs each)
W = np.random.randn(4, 3)

# Step 2: Initialize random bias (1 per neuron)
b = np.random.randn(4)

# Step 3: Compute output
Z = X @ (W.T) + b

print("Weights:\n", W)
print("\nBias:\n", b)
print("\nOutput:\n", Z)

Weights:
 [[ 1.49845688 -1.36751215  0.31821724]
 [-0.97340705 -0.77166496  0.01077436]
 [-0.96718551 -0.51717606  0.93293336]
 [-0.37610632  1.05705184  0.12159993]]

Bias:
 [-0.34751369 -0.28830612  0.26055088 -1.69342705]

Output:
 [[-0.62942937 -2.77272     1.05781335  0.40937008]
 [ 0.71805656 -7.97561292 -0.59647126  2.8170064 ]]
