# LSTM

## Step 1: Import Libraries

In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

## Step 2: Sample Data

In [3]:
# 1) Small number of sentences

sentences = [
    "I love machine learning",
    "Deep learning is powerful",
    "AI is the future"
]

In [43]:
# 2) Large number of sentences
sentences = [
    "I love learning about artificial intelligence",
    "Machine learning models can improve over time",
    "Deep learning is a subset of machine learning",
    "Natural language processing helps computers understand text",
    "I enjoy working on data science projects",
    "Python is a popular language for machine learning",
    "Neural networks are inspired by the human brain",
    "Natural language processing is transforming many industries",
    "Data preprocessing is an important step in machine learning",
    "Feature engineering improves model performance",
    "I am building a model to predict stock prices",
    "Time series analysis is useful for forecasting",
    "Chatbots use natural language processing techniques",
    "Transformers have improved NLP significantly",
    "Recurrent neural networks process sequential data",
    "LSTM helps solve the vanishing gradient problem",
    "GRU is a simpler version of LSTM",
    "I am training my model using TensorFlow",
    "Keras provides an easy way to build neural networks",
    "Model evaluation is crucial in machine learning",
    "Overfitting occurs when the model memorizes data",
    "Regularization helps reduce overfitting",
    "Cross validation improves model reliability",
    "Gradient descent is used to optimize models",
    "Loss functions measure model performance",
    "Activation functions introduce non linearity",
    "I am learning about deep learning architectures",
    "Convolutional neural networks are used for images",
    "Computer vision is an exciting field in AI",
    "Speech recognition converts voice into text",
    "Text generation models can write sentences",
    "Language models learn patterns in text data",
    "Tokenization converts text into numbers",
    "Word embeddings capture semantic meaning",
    "I am experimenting with different hyperparameters",
    "Batch size affects training speed",
    "Epochs define how many times data is processed",
    "Optimization algorithms improve convergence",
    "Adam optimizer is widely used in deep learning",
    "I am working on Natural language processing",
    "Sequence models are useful for text prediction",
    "Predicting the next word is a common NLP task",
    "AI systems require large amounts of data",
    "Data cleaning is necessary before training models",
    "I enjoy teaching machine learning concepts",
    "Students are learning Natural language processing",
    "This course covers LSTM and GRU models",
    "Understanding Natural language processing in AI",
    "Building projects helps in learning faster",
    "Natural language processing is important"
]


## Step 3: Tokenization

In [44]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[4, 51, 2, 29, 52, 53], [11, 2, 6, 30, 31, 54, 32], [21, 2, 1, 13, 55, 22, 11, 2], [7, 3, 8, 15, 56, 57, 12], [4, 33, 34, 35, 5, 58, 36], [59, 1, 13, 60, 3, 16, 11, 2], [17, 18, 19, 61, 62, 20, 63, 64], [7, 3, 8, 1, 65, 37, 66], [5, 67, 1, 23, 38, 68, 9, 11, 2], [69, 70, 39, 10, 40], [4, 14, 41, 13, 10, 24, 71, 72, 73], [32, 74, 75, 1, 42, 16, 76], [77, 78, 7, 3, 8, 79], [80, 81, 82, 43, 83], [84, 17, 18, 85, 86, 5], [25, 15, 87, 20, 88, 44, 89], [45, 1, 13, 90, 91, 22, 25], [4, 14, 26, 92, 10, 93, 94], [95, 96, 23, 97, 98, 24, 99, 17, 18], [10, 100, 1, 101, 9, 11, 2], [46, 102, 103, 20, 10, 104, 5], [105, 15, 106, 46], [107, 108, 39, 10, 109], [44, 110, 1, 27, 24, 111, 6], [112, 47, 113, 10, 40], [114, 47, 115, 116, 117], [4, 14, 2, 29, 21, 2, 118], [119, 17, 18, 19, 27, 16, 120], [121, 122, 1, 23, 123, 124, 9, 28], [125, 126, 48, 127, 49, 12], [12, 128, 6, 30, 129, 130], [3, 6, 131, 132, 9, 12, 5], [133, 48, 12, 49, 134], [50, 135, 136, 137, 138], [4, 14, 139, 140, 141, 142], [143, 

## Step 4: Create Input-Output Pairs

In [45]:
X = []
y = []

for seq in sequences:
    for i in range(1, len(seq)):
        X.append(seq[:i])
        y.append(seq[i])

X = pad_sequences(X)
y = np.array(y)

In [23]:
print(X[:3])
print(y[:3])

[[ 0  0  0  0  0  0  0  4]
 [ 0  0  0  0  0  0  4 52]
 [ 0  0  0  0  0  4 52  2]]
[52  2 21]


## Step 5: Build LSTM Model

In [46]:
vocab_size = len(tokenizer.word_index) + 1 # +1 is for padding (index 0)
print(vocab_size)

180


In [47]:
vocab_size = len(tokenizer.word_index) + 1

model = Sequential([
    Embedding(input_dim=vocab_size, 
              output_dim=10, 
              input_length=X.shape[1]),
    LSTM(64), # GRU(64), # For GRU: Replace LSTM with GRU
    Dense(vocab_size, activation='softmax')
])


## Step 6: Compile Model

In [48]:
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

## Step 7: Train

In [49]:
model.fit(X, y, epochs=100)

Epoch 1/100
9/9 [==============================] - 3s 7ms/step - loss: 5.1915 - accuracy: 0.0143
Epoch 2/100
9/9 [==============================] - 0s 6ms/step - loss: 5.1803 - accuracy: 0.0464
Epoch 3/100
9/9 [==============================] - 0s 6ms/step - loss: 5.1614 - accuracy: 0.0500
Epoch 4/100
9/9 [==============================] - 0s 7ms/step - loss: 5.1020 - accuracy: 0.0500
Epoch 5/100
9/9 [==============================] - 0s 7ms/step - loss: 4.9288 - accuracy: 0.0500
Epoch 6/100
9/9 [==============================] - 0s 7ms/step - loss: 4.8165 - accuracy: 0.0500
Epoch 7/100
9/9 [==============================] - 0s 9ms/step - loss: 4.7615 - accuracy: 0.0500
Epoch 8/100
9/9 [==============================] - 0s 8ms/step - loss: 4.7446 - accuracy: 0.0571
Epoch 9/100
9/9 [==============================] - 0s 6ms/step - loss: 4.7278 - accuracy: 0.0429
Epoch 10/100
9/9 [==============================] - 0s 6ms/step - loss: 4.7228 - accuracy: 0.0464
Epoch 11/100
9/9 [===========

# Now we use the model: Predict next word

The flow

```
Text → Tokenizer → Sequence → Padding → Model → Prediction → Convert back to word


## Step 1: Input sentence

In [50]:
# input_text = "I love"

In [58]:
# For longer sentences use following:

input_text = "I love"
# input_text = "Natural language"



## Step 2: Convert to sequence

In [59]:
seq = tokenizer.texts_to_sequences([input_text])
print(seq)

[[4, 51]]


## Step 3: Pad sequence (VERY IMPORTANT)

Model expects same length as training data

In [60]:
seq = pad_sequences(seq, maxlen=X.shape[1])
print(seq)

[[ 0  0  0  0  0  0  4 51]]


## Step 4: Predict

In [61]:
pred = model.predict(seq)
print(pred)

1/1 [==============================] - 0s 40ms/step
[[1.1059138e-05 8.5856579e-03 9.6390933e-02 5.5170525e-04 1.1327555e-05
  2.1299084e-03 2.0396518e-02 2.5653050e-03 6.5634995e-05 2.6171331e-03
  6.7391545e-03 7.2637387e-03 1.5934883e-02 4.3372279e-03 4.2060517e-02
  6.2076072e-03 5.3736907e-03 3.5539451e-03 5.6606713e-03 1.9652346e-02
  1.7222574e-02 5.0362847e-03 1.5541555e-02 1.2541598e-03 1.4808993e-03
  6.6237203e-03 3.4091301e-02 4.6765166e-03 1.4842141e-03 2.1592412e-02
  2.9655546e-02 1.7830836e-02 2.1097559e-04 2.3831317e-02 5.3105358e-02
  1.3629169e-02 6.9254322e-04 9.9213282e-03 2.2513862e-04 2.3831073e-02
  2.6772206e-04 2.0800583e-02 1.5157966e-02 9.7203936e-04 3.6214333e-05
  1.3549185e-04 1.8028369e-03 2.1978816e-02 1.2164016e-02 3.3474315e-03
  5.8875089e-03 9.9527054e-03 1.2019498e-03 8.6086984e-05 1.4991439e-03
  1.1055686e-03 6.2149309e-04 1.5227869e-03 2.5326820e-04 7.8911080e-06
  5.1942357e-04 1.3651291e-02 6.4611128e-03 1.0604503e-04 6.9565094e-06
  3.6059303e

## Step 5: Get predicted word index

In [62]:
predicted_index = np.argmax(pred)
print(predicted_index)

2


## Step 6: Convert index → word

In [63]:
for word, index in tokenizer.word_index.items():
    if index == predicted_index:
        print(word)


learning


# Generate full Sentence

In [64]:
def generate_text(seed_text, next_words):
    for _ in range(next_words):
        seq = tokenizer.texts_to_sequences([seed_text])
        seq = pad_sequences(seq, maxlen=X.shape[1])

        pred = model.predict(seq)
        predicted_index = np.argmax(pred)

        output_word = ""
        for word, index in tokenizer.word_index.items():
            if index == predicted_index:
                output_word = word
                break

        seed_text += " " + output_word

    return seed_text

print(generate_text("I love", 3))

1/1 [==============================] - 0s 29ms/step
I love learning about artificial
