In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    "I went to bed early",
    "Deep learning is powerful",
    "NLP is fascinating"
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index
print(word_index)

{'is': 1, 'i': 2, 'went': 3, 'to': 4, 'bed': 5, 'early': 6, 'deep': 7, 'learning': 8, 'powerful': 9, 'nlp': 10, 'fascinating': 11}


In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    "I went to bed early",
    "Deep learning is powerful",
    "NLP is fascinating"
]

sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[2, 3, 4, 5, 6], [7, 8, 1, 9], [10, 1, 11]]


In [5]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    "I went to bed early",
    "Deep learning is powerful",
    "NLP is fascinating"
]

sequences = tokenizer.texts_to_sequences(sentences)
padded = pad_sequences(sequences, padding='post')
print(padded)

[[ 2  3  4  5  6]
 [ 7  8  1  9  0]
 [10  1 11  0  0]]


In [ ]:
from tensorflow.keras.layers import Embedding

embedding_layer = Embedding(
    input_dim=1000,   # vocabulary size
    output_dim=16,    # vector size
    input_length=4    # length after padding
)


# Application: 
## Sentiment Analysis -> NLP Pipeline + RNN Model

# Step 1: Dataset

In [15]:
# sentences = [
#     "I love this product",
#     "This is amazing",
#     "I hate this",
#     "Very bad experience"
# ]
# labels = np.array([1, 1, 0, 0])


In [22]:
sentences = [
    # Positive
    "I love this product",
    "This is amazing",
    "Absolutely fantastic experience",
    "I really enjoyed this",
    "Best purchase ever",
    "Super happy with the quality",
    "This is wonderful",
    "Highly recommend this",
    "I am very satisfied",
    "It works perfectly",
    "Brilliant product",
    "Very good experience",
    "I like this a lot",
    "Excellent service",
    "Totally worth it",
    "I am impressed",
    "Loved it",
    "Five stars",
    "Very useful and reliable",
    "Great value for money",
    "This made my day",
    "I would buy again",
    "Extremely happy",
    "Perfect choice",
    "Outstanding quality",

    # Negative
    "I hate this",
    "Very bad experience",
    "This is terrible",
    "Worst product ever",
    "I am disappointed",
    "Not worth the money",
    "Very bad quality",
    "I regret buying this",
    "Awful experience",
    "Completely useless",
    "This is not good",
    "Poor performance",
    "Very frustrating",
    "I dislike this",
    "Waste of money",
    "Terrible service",
    "Not recommended",
    "It broke quickly",
    "Very low quality",
    "Bad choice",
    "Extremely unhappy",
    "This is disappointing",
    "Horrible product",
    "Does not work properly",
    "I will not buy again"
]

labels = [
    # 25 Positive (1)
    1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,

    # 25 Negative (0)
    0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0
]


# Step 2: Tokenization

In [23]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index
print("Word Index:", word_index)


Word Index: {'<OOV>': 1, 'this': 2, 'i': 3, 'very': 4, 'is': 5, 'not': 6, 'product': 7, 'experience': 8, 'quality': 9, 'it': 10, 'am': 11, 'money': 12, 'ever': 13, 'happy': 14, 'the': 15, 'good': 16, 'service': 17, 'worth': 18, 'buy': 19, 'again': 20, 'extremely': 21, 'choice': 22, 'bad': 23, 'terrible': 24, 'love': 25, 'amazing': 26, 'absolutely': 27, 'fantastic': 28, 'really': 29, 'enjoyed': 30, 'best': 31, 'purchase': 32, 'super': 33, 'with': 34, 'wonderful': 35, 'highly': 36, 'recommend': 37, 'satisfied': 38, 'works': 39, 'perfectly': 40, 'brilliant': 41, 'like': 42, 'a': 43, 'lot': 44, 'excellent': 45, 'totally': 46, 'impressed': 47, 'loved': 48, 'five': 49, 'stars': 50, 'useful': 51, 'and': 52, 'reliable': 53, 'great': 54, 'value': 55, 'for': 56, 'made': 57, 'my': 58, 'day': 59, 'would': 60, 'perfect': 61, 'outstanding': 62, 'hate': 63, 'worst': 64, 'disappointed': 65, 'खराब': 66, 'regret': 67, 'buying': 68, 'awful': 69, 'completely': 70, 'useless': 71, 'poor': 72, 'performance':

# Step 3: Convert Text → Sequences

In [24]:
sequences = tokenizer.texts_to_sequences(sentences)
print("Sequences:", sequences)

Sequences: [[3, 25, 2, 7], [2, 5, 26], [27, 28, 8], [3, 29, 30, 2], [31, 32, 13], [33, 14, 34, 15, 9], [2, 5, 35], [36, 37, 2], [3, 11, 4, 38], [10, 39, 40], [41, 7], [4, 16, 8], [3, 42, 2, 43, 44], [45, 17], [46, 18, 10], [3, 11, 47], [48, 10], [49, 50], [4, 51, 52, 53], [54, 55, 56, 12], [2, 57, 58, 59], [3, 60, 19, 20], [21, 14], [61, 22], [62, 9], [3, 63, 2], [4, 23, 8], [2, 5, 24], [64, 7, 13], [3, 11, 65], [6, 18, 15, 12], [4, 66, 9], [3, 67, 68, 2], [69, 8], [70, 71], [2, 5, 6, 16], [72, 73], [4, 74], [3, 75, 2], [76, 77, 12], [24, 17], [6, 78], [10, 79, 80], [4, 81, 9], [23, 22], [21, 82], [2, 5, 83], [84, 7], [85, 6, 86, 87], [3, 88, 6, 19, 20]]


# Step 4: Padding

In [25]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_sequences = pad_sequences(sequences, padding='post')

print("Padded Sequences:\n", padded_sequences)

Padded Sequences:
 [[ 3 25  2  7  0]
 [ 2  5 26  0  0]
 [27 28  8  0  0]
 [ 3 29 30  2  0]
 [31 32 13  0  0]
 [33 14 34 15  9]
 [ 2  5 35  0  0]
 [36 37  2  0  0]
 [ 3 11  4 38  0]
 [10 39 40  0  0]
 [41  7  0  0  0]
 [ 4 16  8  0  0]
 [ 3 42  2 43 44]
 [45 17  0  0  0]
 [46 18 10  0  0]
 [ 3 11 47  0  0]
 [48 10  0  0  0]
 [49 50  0  0  0]
 [ 4 51 52 53  0]
 [54 55 56 12  0]
 [ 2 57 58 59  0]
 [ 3 60 19 20  0]
 [21 14  0  0  0]
 [61 22  0  0  0]
 [62  9  0  0  0]
 [ 3 63  2  0  0]
 [ 4 23  8  0  0]
 [ 2  5 24  0  0]
 [64  7 13  0  0]
 [ 3 11 65  0  0]
 [ 6 18 15 12  0]
 [ 4 66  9  0  0]
 [ 3 67 68  2  0]
 [69  8  0  0  0]
 [70 71  0  0  0]
 [ 2  5  6 16  0]
 [72 73  0  0  0]
 [ 4 74  0  0  0]
 [ 3 75  2  0  0]
 [76 77 12  0  0]
 [24 17  0  0  0]
 [ 6 78  0  0  0]
 [10 79 80  0  0]
 [ 4 81  9  0  0]
 [23 22  0  0  0]
 [21 82  0  0  0]
 [ 2  5 83  0  0]
 [84  7  0  0  0]
 [85  6 86 87  0]
 [ 3 88  6 19 20]]


# Step 5: Build RNN Model

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

vocab_size = len(word_index) + 1
max_length = padded_sequences.shape[1]

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=16, input_length=max_length),
    SimpleRNN(32),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 5, 16)             1424      
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 32)                1568      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 3025 (11.82 KB)
Trainable params: 3025 (11.82 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Step 6: Train Model

In [27]:
import numpy as np
labels = np.array(labels) # convert to numpy array

model.fit(padded_sequences, labels, epochs=20, verbose=1)

Epoch 1/20
2/2 [==============================] - 2s 7ms/step - loss: 0.6900 - accuracy: 0.6000
Epoch 2/20
2/2 [==============================] - 0s 8ms/step - loss: 0.6831 - accuracy: 0.6800
Epoch 3/20
2/2 [==============================] - 0s 7ms/step - loss: 0.6774 - accuracy: 0.8000
Epoch 4/20
2/2 [==============================] - 0s 7ms/step - loss: 0.6711 - accuracy: 0.8200
Epoch 5/20
2/2 [==============================] - 0s 7ms/step - loss: 0.6650 - accuracy: 0.8600
Epoch 6/20
2/2 [==============================] - 0s 10ms/step - loss: 0.6576 - accuracy: 0.8400
Epoch 7/20
2/2 [==============================] - 0s 10ms/step - loss: 0.6492 - accuracy: 0.8600
Epoch 8/20
2/2 [==============================] - 0s 10ms/step - loss: 0.6396 - accuracy: 0.9400
Epoch 9/20
2/2 [==============================] - 0s 10ms/step - loss: 0.6287 - accuracy: 0.9400
Epoch 10/20
2/2 [==============================] - 0s 7ms/step - loss: 0.6156 - accuracy: 0.9400
Epoch 11/20
2/2 [==================

In [30]:
test_sentences = [
    "I really love this",
    "This is bad"
]

test_seq = tokenizer.texts_to_sequences(test_sentences)
test_pad = pad_sequences(test_seq, maxlen=max_length, padding='post')

predictions = model.predict(test_pad)

for i, sentence in enumerate(test_sentences):
    prob = predictions[i][0]
    if prob >= 0.5:
        label = "Positive"
    else:
        label = "Negative"
        
    print(f"{sentence} → {label} ({prob:.2f})")


1/1 [==============================] - 0s 37ms/step
I really love this → Positive (0.73)
This is bad → Negative (0.37)


# OPTIONAL - Better model

In [33]:
# 1)
from tensorflow.keras.layers import LSTM
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
# print("Word Index:", word_index)


sequences = tokenizer.texts_to_sequences(sentences)
# print("Sequences:", sequences)


from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_sequences = pad_sequences(sequences, padding='post')
# print("Padded Sequences:\n", padded_sequences)


vocab_size = len(word_index) + 1
max_length = padded_sequences.shape[1]
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=16, input_length=max_length),
    LSTM(32),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 5, 16)             1424      
                                                                 
 lstm_1 (LSTM)               (None, 32)                6272      
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 7729 (30.19 KB)
Trainable params: 7729 (30.19 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [34]:
import numpy as np
labels = np.array(labels) # convert to numpy array

model.fit(padded_sequences, labels, epochs=20, verbose=1)

Epoch 1/20
2/2 [==============================] - 3s 8ms/step - loss: 0.6930 - accuracy: 0.5600
Epoch 2/20
2/2 [==============================] - 0s 10ms/step - loss: 0.6926 - accuracy: 0.5400
Epoch 3/20
2/2 [==============================] - 0s 10ms/step - loss: 0.6923 - accuracy: 0.5800
Epoch 4/20
2/2 [==============================] - 0s 9ms/step - loss: 0.6917 - accuracy: 0.6200
Epoch 5/20
2/2 [==============================] - 0s 8ms/step - loss: 0.6912 - accuracy: 0.6800
Epoch 6/20
2/2 [==============================] - 0s 10ms/step - loss: 0.6907 - accuracy: 0.7200
Epoch 7/20
2/2 [==============================] - 0s 9ms/step - loss: 0.6903 - accuracy: 0.6600
Epoch 8/20
2/2 [==============================] - 0s 8ms/step - loss: 0.6894 - accuracy: 0.6800
Epoch 9/20
2/2 [==============================] - 0s 8ms/step - loss: 0.6884 - accuracy: 0.6600
Epoch 10/20
2/2 [==============================] - 0s 9ms/step - loss: 0.6874 - accuracy: 0.6800
Epoch 11/20
2/2 [===================

In [35]:
# 2)
test_sentences = [
    "I really love this",
    "This is bad"
]

test_seq = tokenizer.texts_to_sequences(test_sentences)
test_pad = pad_sequences(test_seq, maxlen=max_length, padding='post')

predictions = model.predict(test_pad)

for i, sentence in enumerate(test_sentences):
    prob = predictions[i][0]
    if prob >= 0.5:
        label = "Positive"
    else:
        label = "Negative"
        
    print(f"{sentence} → {label} ({prob:.2f})")


1/1 [==============================] - 1s 659ms/step
I really love this → Positive (0.52)
This is bad → Negative (0.46)
