In [1]:
import numpy as np

In [2]:
# Transpose for 2D using array.T: nXm matrix becomes mXn matrix 

# Using x.T. It is best for 2D and commonly used in 2D
# e.g.1: If shape of x is 2X3, then shape of x.T becomes 3X2
x = np.array([
    [5, 3, 7], 
    [2, 5 ,9]] 
)
print(x)

transpose = x.T
print(transpose)  

[[5 3 7]
 [2 5 9]]
[[5 2]
 [3 5]
 [7 9]]


In [3]:
# e.g.2: If shape of x is 3X4. Then shape of x.T is 4X3
x = np.array([[6, 2, 3, 4],
              [3, 4, 5, 6],
              [7, 8, 5, 9]]
)
print(x)

transpose = x.T
print(transpose)  

[[6 2 3 4]
 [3 4 5 6]
 [7 8 5 9]]
[[6 3 7]
 [2 4 8]
 [3 5 5]
 [4 6 9]]


In [4]:
# e.g.3: Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    
print(v.T)  

[1 2 3]
[1 2 3]


In [5]:
# Transpose for 2D using np.transpose(): nXm matrix becomes mXn matrix 

# e.g.1: If shape of x is 2X3. Then shape of np.transpose(x) is 3X2
x = np.array([[1, 2, 3], 
              [4, 5 ,6]] 
)
print(x)

transpose = np.transpose(x)
print(transpose)  

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [6]:
# e.g.2: If shape of x is 3X4. Then shape of np.transpose(x) is 4X3
x = np.array([[6, 2, 3, 4],
              [3, 4, 5, 6],
              [7, 8, 5, 9]]
)
print(x)

transpose = np.transpose(x)
print(transpose)

[[6 2 3 4]
 [3 4 5 6]
 [7 8 5 9]]
[[6 3 7]
 [2 4 8]
 [3 5 5]
 [4 6 9]]
