# Set up
Need tensorflow==2.18.0 
- (tensorflow-gpu and tensorflow are the same package since the release of version 2.1. Installing tensorflow alone will enable GPU acceleration.)

In [ ]:
# !pip install tensorflow

In [2]:
import tensorflow as tf

print(tf.__version__)

2.18.0


c:\Users\hi\Desktop\projects\python_projects\tutorial\tut_tensorflow\.venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


## Hello World


In [1]:
import tensorflow as tf

msg = tf.constant('Hello, TensorFlow!')
tf.print(msg)

c:\Users\hi\Desktop\projects\python_projects\tutorial\tut_tensorflow\.venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


Hello, TensorFlow!


## GPU installed ?
Check if GPU is available

In [2]:
import tensorflow as tf

# Check if GPU is available
gpu_available = tf.config.list_physical_devices('GPU')

if gpu_available:
    print("TensorFlow is installed as GPU version.")
else:
    print("TensorFlow is installed as CPU version.")

TensorFlow version -  2.18.0
TensorFlow is installed as CPU version.


## Eager Execution
In TensorFlow 2.x, eager execution is enabled by default, meaning **operations are evaluated immediately**. This is in contrast to the previous version (v1.x), where operations were added to a computational graph and executed only when a session was run.

To check if eager execution is enabled in your environment, you can run this code:

In [3]:
print("Eager execution enabled:", tf.executing_eagerly())

Eager execution enabled: True


In [4]:
import tensorflow as tf

# Scalar (0D tensor)
scalar = tf.constant(5)
print("Scalar:", scalar)

print(f"Scalar:{scalar}")

Scalar: tf.Tensor(5, shape=(), dtype=int32)
Scalar:5


In [5]:
# Vector (1D tensor)

vector = tf.constant([1, 2, 3])
print("Vector:", vector)
print(f"Vector:{vector}")

Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Vector:[1 2 3]


In [9]:
# Matrix (2D tensor)
matrix = tf.constant([[1, 2],
                      [3, 4]]
)
print("Matrix:", matrix)

print("******************")

# 3D Tensor
tensor_3d = tf.constant([[[1], [2]], [[3], [4]]])
print("3D Tensor:", tensor_3d)

Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
******************
3D Tensor: tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


## TensorFlow Variables
In TensorFlow, Variables are used to store and update values during the training process. Unlike constants, they are mutable and can be updated.

In [7]:
import tensorflow as tf

# Create a variable initialized to 0
var = tf.Variable(0, dtype=tf.int32)
print("Initial Variable:", var.numpy())

# Update the variable by adding 5
var.assign_add(5)
print("Updated Variable:", var.numpy())

Initial Variable: 0
Updated Variable: 5


## Basic operations
TensorFlow allows you to perform various mathematical operations on tensors.

## Addition

In [10]:
vector = tf.constant([1, 2, 3])

tensor_add = tf.add(vector, [4, 5, 6])
print("Addition of vector:", tensor_add)

Addition of vector: tf.Tensor([5 7 9], shape=(3,), dtype=int32)


## Multiplication

In [11]:
tensor_mult = tf.multiply(vector, 3)
print("Multiplication of vector by 3:", tensor_mult)

Multiplication of vector by 3: tf.Tensor([3 6 9], shape=(3,), dtype=int32)


In [12]:
# Matrix multiplication

matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
matrix_mult = tf.matmul(matrix_a, matrix_b)

print("Matrix multiplication result:\n", matrix_mult)

Matrix multiplication result:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## TensorFlow Functions and Control Flow
You can define functions in TensorFlow to apply transformations or operations repeatedly. TensorFlow provides control flow operations like tf.while_loop, tf.cond, etc., for conditional operations.

Example (Conditional execution using tf.cond):

In [14]:
# Implement following condional logic:
# if x > 0:
#    then multiply by 2 
# else:
#     subtract 2
    
import tensorflow as tf

def conditional_example(x):
    # tf.cond allows conditional execution based on a condition
    return tf.cond(x > 0, lambda: x * 2, lambda: x - 2)

# Test with positive value
print("Result with positive x (5):", conditional_example(tf.constant(5)).numpy())

# Test with negative value
print("Result with negative x (-3):", conditional_example(tf.constant(-3)).numpy())

Result with positive x (5): 10
Result with negative x (-3): -5
