In [10]:
import numpy as np

In [11]:
# Linear Congruential Generator (LCG)
# step1: Using plain python

def lcg(seed, a=5, c=3, m=16, n=10):
    numbers = [seed]
    x = seed
    for _ in range(n-1):
        x = (a * x + c) % m
        numbers.append(x)
    return numbers


# Call above. Generate 10 random numbers
sequence = lcg(seed=7, n=10)
print(sequence)

# Above is OK for upto 10K random numbers. The speed would go down as numbers increase

[7, 6, 1, 8, 11, 10, 5, 12, 15, 14]


In [12]:
# step2: Using numpy for generating 1 million+ random numbers

def lcg_numpy(seed, a=5, c=3, m=16, n=10):
    numbers = np.empty(n, dtype=np.int64)
    numbers[0] = seed
    for i in range(1, n):
        numbers[i] = (a * numbers[i-1] + c) % m
    return numbers

# Call above. Generate 10 random numbers
sequence = lcg_numpy(7, n=10)
print(sequence)

[ 7  6  1  8 11 10  5 12 15 14]


In [13]:
# Middle Square Method

def middle_square(seed, n=10, width=4):
    """
    seed  : initial seed (int)
    n     : number of random numbers to generate
    width : number of digits to keep (e.g., 4 → middle 4 digits)
    """
    numbers = np.empty(n, dtype=np.int64)
    x = seed
    for i in range(n):
        numbers[i] = x
        sq = str(x * x).zfill(width * 2)  # ensure enough digits with leading zeros
        mid = len(sq) // 2
        x = int(sq[mid - width//2 : mid + width//2])
    return numbers

sequence = middle_square(seed=5735, n=10, width=4)
print(sequence)


[5735 8902 2456  319 1017  342 1169 3665 4322 6796]


In [14]:
# Blum Blum Shub

def bbs(seed, p, q, n=10):
    """
    seed : initial value
    p, q : large primes
    n    : how many numbers to generate
    """
    M = p * q
    numbers = np.empty(n, dtype=np.int64)
    x = seed
    for i in range(n):
        numbers[i] = x
        x = (x * x) % M
    return numbers

sequence = bbs(seed=5, p=7, q=11, n=10)
print(sequence)


[ 5 25  9  4 16 25  9  4 16 25]
