# Step-by-Step Implementation

Example: Single Neuron Training

# Step 1: Setup

In [9]:
import tensorflow as tf

# Input and true output
X = tf.constant([[1.0, 2.0, 3.0]])
y_true = tf.constant([[10.0]])

# Step 2: Initialize Weights - Random

In [10]:
W = tf.Variable([[0.5], [0.3], [-0.2]])
b = tf.Variable([0.1])

# Step 3: Forward + Backward Pass

Flow
- Forward pass: Compute prediction
- Loss: Measure error
- Backward: Use calculus to adjust weights to reduce loss

In [11]:
learning_rate = 0.01

for epoch in range(10):
    with tf.GradientTape() as tape:
       
        # Forward pass
        z = tf.matmul(X, W) + b
        y_pred = tf.nn.relu(z) # Activation (ReLU)
        
        # Loss (MSE)
        loss = tf.reduce_mean((y_true - y_pred) ** 2)

    # Backward pass (gradients)
    grads = tape.gradient(loss, [W, b])

    # Update weights
    W.assign_sub(learning_rate * grads[0])
    b.assign_sub(learning_rate * grads[1])

    print(f"Epoch {epoch}: Loss = {loss.numpy()}")

Epoch 0: Loss = 88.35999298095703
Epoch 1: Loss = 43.2963981628418
Epoch 2: Loss = 21.215240478515625
Epoch 3: Loss = 10.395463943481445
Epoch 4: Loss = 5.093780040740967
Epoch 5: Loss = 2.495950698852539
Epoch 6: Loss = 1.2230165004730225
Epoch 7: Loss = 0.5992785096168518
Epoch 8: Loss = 0.29364699125289917
Epoch 9: Loss = 0.14388667047023773


In [14]:
# print W and b
print("W:", W)
print("b:", b)

W: <tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.1089648],
       [1.5179299],
       [1.6268946]], dtype=float32)>
b: <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.7089649], dtype=float32)>


In [13]:
# prediction
X = tf.constant([[1.0, 2.0, 3.0]])
z = tf.matmul(X, W) + b
y_pred = tf.nn.relu(z) # Activation (ReLU)
print(y_pred)

tf.Tensor([[9.734473]], shape=(1, 1), dtype=float32)


# Extend to Multi-Neuron Layer

In [5]:
# Input (2 samples, 3 features)
X = tf.constant([
    [1.0, 2.0, 3.0],
    [2.0, 5.0, -1.0]
])

# True outputs (2 samples, 3 neurons)
y_true = tf.constant([
    [1.0, 0.0, 1.0],
    [0.0, 1.0, 0.0]
])

# Weights (3 inputs → 3 neurons)
W = tf.Variable(tf.random.normal((3, 3)))
b = tf.Variable(tf.random.normal((3,)))

for epoch in range(10):

    with tf.GradientTape() as tape:
        z = tf.matmul(X, W) + b
        y_pred = tf.nn.relu(z) # activation
        
        loss = tf.reduce_mean((y_true - y_pred) ** 2)

    grads = tape.gradient(loss, [W, b])

    W.assign_sub(0.01 * grads[0])
    b.assign_sub(0.01 * grads[1])

    print(f"Epoch {epoch}: Loss = {loss.numpy()}")


Epoch 0: Loss = 13.101323127746582
Epoch 1: Loss = 10.427319526672363
Epoch 2: Loss = 8.327637672424316
Epoch 3: Loss = 6.677165508270264
Epoch 4: Loss = 5.378214359283447
Epoch 5: Loss = 4.354486465454102
Epoch 6: Loss = 3.5463716983795166
Epoch 7: Loss = 2.907285690307617
Epoch 8: Loss = 2.400810956954956
Epoch 9: Loss = 1.9984639883041382


# Try other activation:
- y_pred = tf.nn.sigmoid(z)
- y_pred = tf.nn.tanh(z)


# 2-Layer Neural Network (From Scratch with Training)
Architecture
```
Input (3 features)
   ↓
Hidden Layer (4 neurons, ReLU)
   ↓
Output Layer (1 neuron)
```


## Core Math

Forward pass:

Z1 = X * W1 + b1

A1 = max(0, Z1)

Z2 = A1 * W2 + b2

In [24]:
import tensorflow as tf

# 1. Data
X = tf.constant([
    [1.0, 2.0, 3.0],
    [2.0, 5.0, -1.0],
    [-1.0, 2.0, 4.0]
])

y_true = tf.constant([
    [1.0],
    [0.0],
    [1.0]
])

# 2. Initialize Weights: # input → hidden
W1 = tf.Variable(tf.random.normal((3, 4)))  
b1 = tf.Variable(tf.zeros((4,)))

# hidden → output
W2 = tf.Variable(tf.random.normal((4, 1)))  
b2 = tf.Variable(tf.zeros((1,)))

learning_rate = 0.01

# 3. Training Loop
for epoch in range(50):

    with tf.GradientTape() as tape:
        # ---- Forward Pass ----
        Z1 = tf.matmul(X, W1) + b1
        A1 = tf.nn.relu(Z1)

        Z2 = tf.matmul(A1, W2) + b2
        y_pred = tf.nn.sigmoid(Z2)   # output activation

        # ---- Loss ----
        loss = tf.reduce_mean((y_true - y_pred) ** 2)

    # ---- Backprop ----
    grads = tape.gradient(loss, [W1, b1, W2, b2])

    # ---- Update ----
    W1.assign_sub(learning_rate * grads[0])
    b1.assign_sub(learning_rate * grads[1])
    W2.assign_sub(learning_rate * grads[2])
    b2.assign_sub(learning_rate * grads[3])

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.numpy()}")

Epoch 0, Loss: 0.08311276137828827
Epoch 10, Loss: 0.0713438019156456
Epoch 20, Loss: 0.06192098557949066
Epoch 30, Loss: 0.05428051948547363
Epoch 40, Loss: 0.04801684245467186


In [27]:
# 4. Final Predictions
X_sample = tf.constant([
    [1.0, 2.0, 3.0],
    [2.0, 5.0, -1.0],
    [-1.0, 2.0, 4.0]
])
Z1 = tf.matmul(X_sample, W1) + b1
A1 = tf.nn.relu(Z1)

Z2 = tf.matmul(A1, W2) + b2
y_pred = tf.nn.sigmoid(Z2)   

print("\nFinal Predictions:\n", y_pred.numpy())


Final Predictions:
 [[0.65588886]
 [0.06613322]
 [0.9244546 ]]


# Redo above using Kera (5 lines of code)

In [26]:
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(4, activation='relu', 
                       input_shape=(3,)),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='mse')
model.fit(X, y_true, epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.2985
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 0.2956
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.2926
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.2897
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.2868
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 0.2839
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.2809
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 0.2780
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.2751
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.2722
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.2693
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.2663
Epoch 13/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.2634
Epoch 14/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.2605
Epoch 15/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.2576
Epoch 16/50
1/1 ━━━━━━━━━━━━━━━━━━━━

In [23]:
X_sample = tf.constant([
    [1.0, 2.0, 3.0],
    [2.0, 5.0, -1.0],
    [-1.0, 2.0, 4.0]
])

predictions = model.predict(X_sample)
print("Predictions:\n", predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step
Predictions:
 [[0.73357576]
 [0.9289641 ]
 [0.53579915]]
