In [1]:
import numpy as np

In [2]:
# flatten(): It returns copy

# lets flatten 2D array to 1D array

# Create a 2D NumPy array (matrix) of shape 3X3
a = np.array([[5, 3, 3],
              [1, 5, 6],
              [7, 8, 9]]
)

print("Original Array:\n",a)

# Flatten the 2D array into a 1D array
flattened_array = a.flatten()

print("\nFlattened Array:", flattened_array)
print("number of elements:", len(flattened_array))

Original Array:
 [[5 3 3]
 [1 5 6]
 [7 8 9]]

Flattened Array: [5 3 3 1 5 6 7 8 9]
number of elements: 9


In [3]:
# lets flatten 3D array to 1D array

# Create a 3D NumPy array (matrix) of shape 2X3X5
a = np.array([
    [  # First block (depth index 0)
        [9, 5, 3, 4, 5],      # row=0
        [1, 7, 8, 9, 10],     # row=1
        [11, 12, 13, 14, 15]  # row=2
    ],
    
    [  # Second block (depth index 1)
        [16, 17, 18, 19, 20], # row=0
        [21, 22, 23, 24, 25], # row=1
        [26, 27, 28, 29, 30]  # row=2
    ]
])

print("Original Array:\n",a)

# Flatten the 2D array into a 1D array
flattened_array = a.flatten()

print("\nFlattened Array:", flattened_array)
print("number of elements:", len(flattened_array))

Original Array:
 [[[ 9  5  3  4  5]
  [ 1  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]

Flattened Array: [ 9  5  3  4  5  1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
number of elements: 30


In [4]:
# ravel: Modifying the raveled array can affect the original array

a = np.array([[1, 2, 3],
              [4, 5, 6]]
)
print("array a:\n", a)

raveled_arr = a.ravel()
print("raveled array:\n", raveled_arr)

# Modifying raveled_arr effects a
raveled_arr[0] = 99
print("array a:\n", a) # a is changed

array a:
 [[1 2 3]
 [4 5 6]]
raveled array:
 [1 2 3 4 5 6]
array a:
 [[99  2  3]
 [ 4  5  6]]


In [5]:
# Reshape: lets reshape a flattened array

# Create a flattened array of size 18: 0,1,2,..17
a = np.arange(18) 
print("Flattened Array:", a)

# Reshape into different sizes

# 1. Reshape to 2D array of shape (2, 9)
reshaped_2d_2x9 = a.reshape(2, 9)
print("\nReshaped Array (2x9):\n",reshaped_2d_2x9)
print(type(reshaped_2d_2x9), reshaped_2d_2x9.ndim)
print(reshaped_2d_2x9.shape) # (2, 9)          

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (2x9):
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]
<class 'numpy.ndarray'> 2
(2, 9)


In [6]:
a = np.arange(18) 
print("Flattened Array:", a)

# 2. Reshape to 2D array of shape (3, 6)
reshaped_2d_3x6 = a.reshape(3, 6)
print("\nReshaped Array (3x6):\n",reshaped_2d_3x6)

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (3x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [10]:
a = np.arange(18) 
print("Flattened Array:", a)

# 3. Reshape to 2D array of shape (6, 3)
reshaped_2d_6x3 = a.reshape(6, 3)
print("\nReshaped Array (6x3):\n",reshaped_2d_6x3)

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (6x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [11]:
a = np.arange(18) 
print("Flattened Array:", a)

# 4. Reshape to 3D array of shape (2, 3, 3)
reshaped_3d_2x3x3 = a.reshape(2, 3, 3)
print("\nReshaped Array (2x3x3):\n",reshaped_3d_2x3x3)

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (2x3x3):
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [13]:
a = np.arange(18) 
print("Flattened Array:", a)

# 5. Reshape to 3D array of shape (3, 2, 3)
reshaped_3d_3x2x3 = a.reshape(3, 2, 3)
print("\nReshaped Array (3x2x3):\n", reshaped_3d_3x2x3)

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (3x2x3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [14]:
# Another way to flatten is to use reshape with argument -1:
# -1 means that numpy would figure out the shape.

# 3D array to 1D array:

arr = np.array([[1, 2, 3, 4, 5],
                [4, 5, 6, 7, 8],
                [7, 8, 9, 3, 4]]
)
print(arr)

# convert it into 1D
reshaped = arr.reshape((-1))
print(reshaped)
#####################

[[1 2 3 4 5]
 [4 5 6 7 8]
 [7 8 9 3 4]]
[1 2 3 4 5 4 5 6 7 8 7 8 9 3 4]


In [15]:
arr = np.array([[1, 2, 3, 4, 5],
                [4, 5, 6, 7, 8],
                [7, 8, 9, 3, 4]]
)
print(arr)

# convert it into 2D of shape 5X3
reshaped = arr.reshape((-1, 3))
print(reshaped)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [7 8 9 3 4]]
[[1 2 3]
 [4 5 4]
 [5 6 7]
 [8 7 8]
 [9 3 4]]


In [16]:
# convert it into 2D of shape 5X3
reshaped = arr.reshape((5, -1))
print(reshaped)

[[1 2 3]
 [4 5 4]
 [5 6 7]
 [8 7 8]
 [9 3 4]]
