# Changing the shape of arrays: flatten(), ravel(), reshape()

### flatten()
- Convert a **multi-dimensional array into a one-dimensional array**. (A 2D array of shape 3X4 changes to 1D array of shape 12)
- flatten() returns **copy**. So modifying the flattened array would not change the original array.

#### Why do we need 1D array ?

- Many Machine Learning models (e.g., logistic regression, decision trees) expect 1D feature vectors, not 2D matrices.
- Many Convolutional Neural Network model requires 1D data 
![2D_to_1D](images/2D_to_1D.png)


**In some cases, the data is spatially distributed and we need it in 1D array**
- Suppose Temperature Sensor Grid (e.g., Smart Building or IoT Device) is mounted on a building and uses a 3×3 array of temperature sensors placed in a room (ceiling tiles or wall grid). Each number represents temperature (°C or °F) at a specific grid point. We flatten the data and then calculate mean, std_dev, etc

In [ ]:
import numpy as np

In [46]:
# lets flatten 2D array to 1D array

# Create a 2D NumPy array (matrix) of shape 3X3
a = np.array([[5, 3, 7],
              [1, 5, 6],
              [7, 8, 9]]
)

print("Original Array:\n",a)

# Flatten the 2D array into a 1D array
flattened_array = a.flatten()

print("\nFlattened Array:", flattened_array)
print("\nFlattened shape:", flattened_array.shape)
print("Number of elements:", len(flattened_array))

Original Array:
 [[5 3 7]
 [1 5 6]
 [7 8 9]]

Flattened Array: [5 3 7 1 5 6 7 8 9]

Flattened shape: (9,)
Number of elements: 9


In [47]:
# lets modify the flattened array and compare with the original array
# Returns a *copy* of the array, collapsed into 1D
# Changes made to the flattened array do NOT affect the original array

# Create a 2D NumPy array (matrix) of shape 3X3
a = np.array([[5, 3, 7],
              [1, 5, 6],
              [7, 8, 9]]
)
print("Original Array:\n",a)

# Flatten the 2D array into a 1D array
flattened_array = a.flatten()
flattened_array[0] = -66

print("\nFlattened Array:", flattened_array)
print("\nFlattened shape:", flattened_array.shape)
print("Number of elements:", len(flattened_array))
print("Original Array(unchanged):\n",a)

Original Array:
 [[5 3 7]
 [1 5 6]
 [7 8 9]]

Flattened Array: [-66   3   7   1   5   6   7   8   9]

Flattened shape: (9,)
Number of elements: 9
Original Array(unchanged):
 [[5 3 7]
 [1 5 6]
 [7 8 9]]


In [48]:
# lets flatten 3D array to 1D array: shape 2X3X5 -> shape 30

# Create a 3D NumPy array (matrix) of shape 2X3X5
a = np.array([
    [  # First block (depth index 0)
        [9, 5, 3, 4, 5],      # row=0
        [1, 7, 8, 9, 10],     # row=1
        [11, 12, 13, 14, 15]  # row=2
    ],
    
    [  # Second block (depth index 1)
        [16, 17, 18, 19, 20], # row=0
        [21, 22, 23, 24, 25], # row=1
        [26, 27, 28, 29, 30]  # row=2
    ]
])

print("Original Array:\n",a)

# Flatten the 2D array into a 1D array
flattened_array = a.flatten()

print("\nFlattened Array:", flattened_array)
print("\nFlattened shape:", flattened_array.shape)
print("Number of elements:", len(flattened_array))

Original Array:
 [[[ 9  5  3  4  5]
  [ 1  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]

Flattened Array: [ 9  5  3  4  5  1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]

Flattened shape: (30,)
Number of elements: 30


## ravel()
- Convert a **multi-dimensional array into a one-dimensional array**. 
- ravel() returns a **view**: **Modifying the raveled array can therefore affect the original array**
- Its different than flatten() because it returns the view

In [49]:
# ravel: Modifying the raveled array affect the original array

a = np.array([[1, 2, 3],
              [4, 5, 6]]
)
print("array a:\n", a)

raveled_arr = a.ravel()
print("raveled array:\n", raveled_arr)

# Modifying raveled_arr effects a
raveled_arr[0] = 99
print("modified array a:\n", a) # a is changed

array a:
 [[1 2 3]
 [4 5 6]]
raveled array:
 [1 2 3 4 5 6]
modified array a:
 [[99  2  3]
 [ 4  5  6]]


## reshape()
- It is the **opposite of the flatten()** operation.
- Reshapes the array to a new shape of the array, **as long as the total number of elements remains the same.**

### Can we reshape an array into any shape?
**No**. For example you cannot reshape an array of shape 8X4 into 4X5 because they both have different number of elements. 

You can reshape 8X4 into 16X2, 4X2X4, 2X8X2, or 2X16 because they all have same number of elements. The reshaped matrix should have same number of elements as original.

### Why reshape?
- Some machine learning libraries (like scikit-learn) expect 2D input: shape (n_samples, n_features).
- Convert flat 1D image to 2D or 3D format
- You need a 2D structure to do matrix multiplication, transpose, or broadcasting.


In [50]:
# Reshape: lets reshape a flattened array of shape 18 -> 2x9

# Create a flattened array of size 18: 0, 1, 2, ..17
a = np.arange(18) 
print("Flattened Array:", a)

# 1. Reshape to 2D array of shape (2, 9)
reshaped_2d_2x9 = a.reshape(2, 9)
print("\nReshaped Array (2x9):\n",reshaped_2d_2x9)
print(reshaped_2d_2x9.ndim)
print(reshaped_2d_2x9.shape) # (2, 9)          

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (2x9):
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]
2
(2, 9)


In [51]:
# Reshape: lets reshape a flattened array of shape 18 -> 3x6

a = np.arange(18) 
print("Flattened Array:", a)

# 2. Reshape to 2D array of shape (3, 6)
reshaped_2d_3x6 = a.reshape(3, 6)
print("\nReshaped Array (3x6):\n",reshaped_2d_3x6)

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (3x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [54]:
# Reshape: lets reshape a flattened array of shape 18 -> 6x3

a = np.arange(18) 
print("Flattened Array:", a)

# 3. Reshape to 2D array of shape (6, 3)
reshaped_2d_6x3 = a.reshape(6, 3)
print("\nReshaped Array (6x3):\n",reshaped_2d_6x3)

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (6x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [55]:
# Reshape: lets reshape a flattened array of shape 18 -> 2x3x3

a = np.arange(18) 
print("Flattened Array:", a)

# 4. Reshape to 3D array of shape (2, 3, 3)
reshaped_3d_2x3x3 = a.reshape(2, 3, 3)
print("\nReshaped Array (2x3x3):\n",reshaped_3d_2x3x3)

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (2x3x3):
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [56]:
# Reshape: lets reshape a flattened array of shape 18 -> 3x2x3

a = np.arange(18) 
print("Flattened Array:", a)

# 5. Reshape to 3D array of shape (3, 2, 3)
reshaped_3d_3x2x3 = a.reshape(3, 2, 3)
print("\nReshaped Array (3x2x3):\n", reshaped_3d_3x2x3)

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (3x2x3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [57]:
# Another way to flatten is to use reshape with argument -1:
# -1 means that numpy would figure out the shape.

# 2D array to 1D array:
arr = np.array([[1, 2, 3, 4, 5],
                [4, 5, 6, 7, 8],
                [7, 8, 9, 3, 4]]
)
print(arr)
print()

# convert it into 1D
reshaped = arr.reshape((-1))
print(reshaped)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [7 8 9 3 4]]

[1 2 3 4 5 4 5 6 7 8 7 8 9 3 4]


In [58]:
# convert it into 2D of shape -1x3 = 5X3

# 2D array to 1D array:
arr = np.array([[1, 2, 3, 4, 5],
                [4, 5, 6, 7, 8],
                [7, 8, 9, 3, 4]]
)
print(arr)
print()

reshaped = arr.reshape((-1, 3))
print(reshaped)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [7 8 9 3 4]]

[[1 2 3]
 [4 5 4]
 [5 6 7]
 [8 7 8]
 [9 3 4]]


In [61]:
# convert it into 2D of shape 5x-1 = 5X3

# 2D array to 1D array:
arr = np.array([[1, 2, 3, 4, 5],
                [4, 5, 6, 7, 8],
                [7, 8, 9, 3, 4]]
)
print(arr)
print()

reshaped = arr.reshape((5, -1))
print(reshaped)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [7 8 9 3 4]]

[[1 2 3]
 [4 5 4]
 [5 6 7]
 [8 7 8]
 [9 3 4]]


In [62]:
#  Summary: Differences between flatten() and ravel()
# --------------------------------------

summary = """
🔹 flatten() → Returns a COPY of the array (changes don't affect the original)
🔹 ravel()   → Returns a VIEW of the array when possible (changes may affect original)
🔹 reshape() → Changes the SHAPE of the array (without changing data)

Use flatten() when you want a separate independent array.
Use ravel() when you just need a quick 1D view of the same data.
Use reshape() when you want to change dimensions (like 2D → 1D or 1D → 2D).
"""

print(summary)


🔹 flatten() → Returns a COPY of the array (changes don't affect the original)
🔹 ravel()   → Returns a VIEW of the array when possible (changes may affect original)
🔹 reshape() → Changes the SHAPE of the array (without changing data)

Use flatten() when you want a separate independent array.
Use ravel() when you just need a quick 1D view of the same data.
Use reshape() when you want to change dimensions (like 2D → 1D or 1D → 2D).

