In [2]:
import numpy as np
from numpy.linalg import det
from numpy.linalg import inv

In [3]:
# Determinant of 2x2 matrix

A = np.array([[2, 1], 
              [3, 5]]
)

det_A = det(A)
print("Determinant of 2x2 matrix A:", round(det_A, 3))

Determinant of 2x2 matrix A: 7.0


In [4]:
# Determinant of 3x3 matrix
A = np.array([[2, 1, 0],
              [0, 1, -1],
              [0, 2, 4]]
)

det_A = det(A)
print("Determinant of 3x3 matrix A:", round(det_A, 3))

Determinant of 3x3 matrix A: 12.0


In [5]:
# Inverse of a 2X2 matrix
A = np.array([[1, 2], 
              [3, 4]])
A_inv = inv(A)
print("Inverse of Matrix:\n", A_inv)

# Verification: A @ A_inv should be an identity matrix
print("\nVerification (A × A_inv should be I):\n", np.round(A @ A_inv)) 

Inverse of Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Verification (A × A_inv should be I):
 [[1. 0.]
 [0. 1.]]


In [6]:
# Inverse of a 3X3 matrix

A = np.array([[2, 1, 0],
              [0, 1, -1],
              [0, 2, 4]])
A_inv = inv(A)
print("Inverse of Matrix:\n", A_inv)

# Verification: A @ A_inv should be an identity matrix
print("\nVerification (A × A_inv should be I):\n",np.round(A @ A_inv)) 

Inverse of Matrix:
 [[ 0.5        -0.33333333 -0.08333333]
 [ 0.          0.66666667  0.16666667]
 [-0.         -0.33333333  0.16666667]]

Verification (A × A_inv should be I):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
