In [ ]:
# !pip install numpy

In [2]:
import numpy as np

In [6]:
# filter: it returns a boolean variables

# Lets say we have following water contaminant reading
cont = [4, 7, 2, 3, 9, 3, 6, 2, 1, 7] 
a = np.array(cont)

# 1 Filter: select elements equal to 3
mask = (a == 3)
# print(mask)
print(a[mask])

# or use this, but sometimes not easy to understand for beginners
print(a[a == 3]) 


[3 3]
[3 3]


In [7]:
# 2 Filter: All elements not equal to 3
mask = (a != 3)
print(a[mask]) 

[4 7 2 9 6 2 1 7]


In [8]:
# 3 Filter: All elem <= 2 # HEALTHY water
mask = (a <= 2)
print(a[mask])     

[2 2 1]


In [10]:
cont = [4, 7, 2, 3, 9, 3, 6, 2, 1, 7] 
a = np.array(cont)

# 5 Filter: All elem > 2 and < 5 # MODERATE
mask = (a > 2) & (a < 5)
print(a[mask]) 

[4 3 3]


In [11]:
# 6 Filter: select elements less than 2 or greater than 4:
mask = (a < 2) | (a > 4)
print(a[mask])

[7 9 6 1 7]


In [13]:
# where(): It return indices ( and not boolean variables)

scores = np.array([78, 45, 62, 33, 90, 50, 72]) 

# Indices where condition is true
indices = np.where(scores > 50)
print(indices)      # (array([2, 3, 4]),)
print(scores[indices]) # [30 40 50]

(array([0, 2, 4, 6], dtype=int64),)
[78 62 90 72]


In [14]:
# Application1: Assigning Pass/Fail grades based on Scores
scores = np.array([78, 45, 62, 33, 90, 50, 72]) # Student scores
results = np.where(scores >= 50, "Pass", "Fail") # Use np.where to assign "Pass" or "Fail"

print("Scores:", scores)
print("Results:", results)

Scores: [78 45 62 33 90 50 72]
Results: ['Pass' 'Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass']


In [15]:
# Application2: Daily temperatures (°C) recorded over a week as Greater than 30 or less

temperatures = np.array([28, 33, 31, 25, 29, 35, 30])

temp_classification = np.where(temperatures > 30, 'Greater than 30', '30 or less')

print("Temperature readings:", temperatures)
print("Classification:", temp_classification)

Temperature readings: [28 33 31 25 29 35 30]
Classification: ['30 or less' 'Greater than 30' 'Greater than 30' '30 or less'
 '30 or less' 'Greater than 30' '30 or less']


In [17]:
# Application 3:  Flag temperatures above 25°C as "Alert", else "Normal"
# Create a 2D NumPy array
# Temperatures (°C) recorded hourly in 3 rooms over 4 hours
temps = np.array([
    # Room1, Room2, Room3
    [22, 26, 24],  # Hour 1
    [23, 27, 26],  # Hour 2
    [25, 28, 23],  # Hour 3
    [21, 24, 27]   # Hour 4
])

status = np.where(temps > 25, "Alert", "Normal")

print("Temperature readings:\n", temps)
print("\nStatus:\n", status)

Temperature readings:
 [[22 26 24]
 [23 27 26]
 [25 28 23]
 [21 24 27]]

Status:
 [['Normal' 'Alert' 'Normal']
 ['Normal' 'Alert' 'Alert']
 ['Normal' 'Alert' 'Normal']
 ['Normal' 'Normal' 'Alert']]
