In [1]:
import numpy as np

In [6]:
# lets create an array of shape (6): i.e. 1D array with 6 elements

l = [50, 30, 72, 65, 59, 22] # scores in 6 subjects
a = np.array(l)   # Create a rank 1(i.e. 1D) array

print(a)
print(type(a))  #  <class 'numpy.ndarray'>
print(a.ndim)   # lets look at dim
print(a.shape)  # Lets look at shape, i.e. the number of elements (6,)

[50 30 72 65 59 22]
<class 'numpy.ndarray'>
1
(6,)


In [7]:
# I can create numpy array from tuples too
t = (50, 30, 72, 65, 59, 22)
a = np.array(t)   # Create a rank 1(i.e. 1D) array

print(a)
print(type(a))  # <class 'numpy.ndarray'>
print(a.ndim)   # lets look at dim
print(a.shape)  # Lets look at shape, i.e. the number of elements (6,)

[50 30 72 65 59 22]
<class 'numpy.ndarray'>
1
(6,)


In [8]:
# Now lets create an array of dimension 2D each with 2 and 3 elements 
# Each row represents a student, each column represents a subject (Math, Science, English)
l = [
    [85, 90, 78],  # Student 1
    [68, 76, 92]   # Student 2
]
scores = np.array(l)

print(scores)
print(scores.ndim)    # 2
print(scores.shape)   # (2, 3)

[[85 90 78]
 [68 76 92]]
2
(2, 3)


In [10]:
# SKIP ADVANCED #################################################
# Creating a 3D array with shape (2, 3, 5)
b = np.array([
    [  # First block (depth index 0)
        [1, 2, 3, 4, 5],      # row1
        [6, 7, 8, 9, 10],     # row2
        [11, 12, 13, 14, 15]  # row3
    ],
    
    [  # Second block (depth index 1)
        [16, 17, 18, 19, 20], # row1
        [21, 22, 23, 24, 25], # row2
        [26, 27, 28, 29, 30]  # row3
    ]
])
print(b)
print(b.ndim)    #  3
print(b.shape)   # (2, 3, 5)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
3
(2, 3, 5)


In [11]:
# lets create an array of shape (2,3,2)
b = np.array([
    [ # First block (depth index 0)
        [1, 2],
        [5, 8],
        [3, 4]
    ],
    [ # Second block (depth index 1)
        [5, 6],
        [3, 0],
        [7, 8]
    ]
])
print(b)
print(b.ndim)    #  3
print(b.shape)   # (2, 3, 2)
##################################################

[[[1 2]
  [5 8]
  [3 4]]

 [[5 6]
  [3 0]
  [7 8]]]
3
(2, 3, 2)


In [13]:
# creating matrices of all zeros
# create a 1D array of 10 elements with all 0

a = np.zeros((100)) 
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [14]:
# Create an 3X3 array of all zeros
a = np.zeros((3,3))   
print(a)              
print(a.ndim)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
(3, 3)


In [15]:
# Create an 3X5 array of all zeros
a = np.zeros((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
a = np.zeros((3,5,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [17]:
# creating matrices of all 1 or some constant
# create arrays of all 1
b = np.ones((4))    
print(b) 

[1. 1. 1. 1.]


In [18]:
# create 3x5 array of all 1
a = np.ones((3,5)) 
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
# fill an array with some constant value 5
a = np.full((3), fill_value=5)
print(a)

[5 5 5]


In [20]:
# fill an 3X4 array with some constant value 9
a = np.full((3,4), fill_value=9)
print(a)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [21]:
# creating identity matrices

# Lets create an array of identity matrix
d = np.eye(3)         
print(d)  

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
#  Lets create an 3X5 array of identity matrix
d = np.eye(3, 5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [23]:
# create array wth random numbers

# Create an 1Darray of size 3 filled with random values between 0 and 1
e = np.random.random((10))  
print(e)

[0.28511682 0.56184549 0.37338554 0.36160918 0.92092651 0.27205543
 0.83695064 0.85546882 0.14875572 0.71714887]


In [24]:
# Create an 2X4 array filled with random values between 0 and 1
e = np.random.random( (2,4) )  
print(e)

[[0.29186614 0.79779978 0.09646059 0.64983328]
 [0.24984665 0.44937615 0.00266141 0.52492033]]


In [27]:
# Generate a 1D array with 8 elements with random integers between -10 (inclusive) and 15 (exclusive)
e = np.random.randint(-10, 15, size=(8,))
print(e)

[-5 -3 13 -3 -5 -3 -8 -6]


In [29]:
# Generate a 2X4X8 matrix with random integers between -10 (inclusive) and 15 (exclusive)
e = np.random.randint(-10, 15, size=(2, 4, 8))
print(e)

[[[  9  -3  -8   8   1   6  -5   2]
  [ -2   8  -9  10  -1  -7   2  -9]
  [-10   0  12  14   9  14   2   5]
  [ 11  13  10  13   4   5  13   9]]

 [[ 14   0  -5  14  12   6   6   7]
  [-10  13  -2  -3  13   3  -8  11]
  [-10  -8   9  10 -10  13  -1  -8]
  [  0  -6  -6  -2   1  -5   7  -1]]]


In [32]:
# creating arrays using method arange(start_idx=0, stop_idx, step=1)

# Example 1: # Creates an array from 0 to 4
arr = np.arange(5)  
print(arr)


[0 1 2 3 4]


In [33]:
# Example 2: Creates an array from 2 to 9
arr = np.arange(2, 10)  
print(arr)


[2 3 4 5 6 7 8 9]


In [34]:
# Example 3: Creates an array from 1 to 9 with a step of 2
arr = np.arange(1, 10, 2)  
print(arr)


[1 3 5 7 9]


In [35]:
# Example 4: Creates an array of floats from 0 to 0.9 with step=0.1
arr = np.arange(0, 1, 0.1)  
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
