In [28]:
import numpy as np

In [32]:
# Element-wise operation: Add/Subtract/mutliply/divide by 10 
x = np.array([[1, 2, 3],
              [4, 5, 6]]
) # 2D array of shape 2X3

# res = x + 10
# res = x - 10
# res = x * 10
res = x / 10

print(res)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [33]:
# Elementwise operation: sqrt, power, exp, log
x = np.array([[1, 2, 3],
              [4, 5, 6]]
) # 2D array of shape 2X3

square_result = np.sqrt(x)
print("Square:\n", square_result)

Square:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [36]:
# Raise each element to the power of 2
x = np.array([[1, 2, 3],
              [4, 5, 6]]
) # 2D array of shape 2X3

power_result = np.power(x, 2)  
print("Power:\n", power_result)

Power:
 [[ 1  4  9]
 [16 25 36]]


In [37]:
# Computes e^x for each element. e is Euler number = 2.718...

x = np.array([[1, 2, 3],
              [4, 5, 6]]
) # 2D array of shape 2X3

exp_result = np.exp(x)  
print("Exponential:\n", exp_result)

Exponential:
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [38]:
# Computes the natural logarithm

x = np.array([[1, 2, 3],
              [4, 5, 6]]
) # 2D array of shape 2X3

log_result = np.log(x)  
print("Natural Logarithm:\n", log_result)

Natural Logarithm:
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [39]:
# Computes the base-10 logarithm

x = np.array([[1, 2, 3],
              [4, 5, 6]]
) # 2D array of shape 2X3

log10_result = np.log10(x)  
print("Base-10 Logarithm:\n", log10_result)

Base-10 Logarithm:
 [[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]


In [40]:
# Elementwise operation for rounding. There are 3 different kinds: floor, ceil, round

x = np.array([[1.1, 2.2, 3.3],
              [4.4, 5.5, 6.6]]
) # 2D array of shape 2X3

floor_result = np.floor(x)  # Rounds down
print("Floor:\n", floor_result)

ceil_result = np.ceil(x)    # Rounds up
print("Ceil:\n", ceil_result)

round_result = np.round(x)   # Rounds to nearest integer
print("Round:\n", round_result)

Floor:
 [[1. 2. 3.]
 [4. 5. 6.]]
Ceil:
 [[2. 3. 4.]
 [5. 6. 7.]]
Round:
 [[1. 2. 3.]
 [4. 6. 7.]]


In [41]:
# A simple application: chaining
# Suppose you have to sqrt all numbers, then multiply by 2 and then add 5 to all elements

x = np.array(
    [[1,2],
     [3,4]]
)

res =  ( np.sqrt(x) * 2 ) + 5
print(res)

[[7.         7.82842712]
 [8.46410162 9.        ]]


In [14]:
# Lets say you want to raise every number in an array by some number that is present in different array
a = np.array([2, 3, 4])
b = np.array([3, 2, 2])

result = np.power(a, b)
print(result)  

[ 8  9 16]


In [42]:
# Lets say you want to find remainder for every number divided by some number that is present in different array
a = np.array([10, 20, 30])
b = np.array([3,  7,  8])

# rem = np.remainder(a, b)
rem = np.mod(a, b)
print(rem)  

[1 6 6]


In [43]:
# Lets say you want to perform floor division on every number by numbers that are present in different array
a = np.array([10, 20, 30])
b = np.array([3,   7,  8])

result = np.floor_divide(a, b)
print(result)  

[3 2 3]


In [44]:
# sum + cumsum
x = np.array([3, 2, 2, 4, -1 ,6]) 
print(np.sum(x)) 

16


In [45]:
# Tracking savings growth over time.
arr = np.array([100, 150, 200, 100, 50]) # monthly_savings
print('array  :', arr)
result = np.cumsum(arr) # Calculate cumulative monthly savings.
print('cum_sum:', result)  

array  : [100 150 200 100  50]
cum_sum: [100 250 450 550 600]


In [46]:
# prod(), cumprod()

# Application:A person 4 outfit_options: 2 shirts, 3 pants, 4 pairs of shoes and 2 ties.
# Finding all possible combinations of items from different categories.
arr = np.array([2, 3, 4, 2]) 
result = np.prod(arr) # Total combinations = 2 * 3 * 4 * 2 = 48
print(result)

48


In [48]:
# Calculate cumulative return on investment where gains compound.
# this is a return: # Example: Yearly return multipliers (e.g., 10% gain → 1.10)
arr = np.array([1.10, 1.05, 0.98, 1.20]) 
print("array :", arr)
result = np.cumprod(arr) # Cumulative compounded return
print("result:", result)  

array : [1.1  1.05 0.98 1.2 ]
result: [1.1     1.155   1.1319  1.35828]


In [49]:
# diff() : Use Case-> Calculate daily increase in website traffic.

arr = np.array([10, 15, 30, 25, 31]) # i.e. visitors 
print("array :", arr)
result = np.diff(arr) # daily increase/decrease
print("result:", result) 

array : [10 15 30 25 31]
result: [ 5 15 -5  6]
