In [8]:
import numpy as np

In [10]:
# Here x could be an image of size 2X2.

# Elementwise addition (e.g., applying a brightness mask y)
x = np.array([[100, 150],
              [140, 200]], dtype=np.float64
)

y = np.array([[5, 10],
              [15, 20]], dtype=np.float64
)

# res = x + y
res = np.add(x, y)
print("Add filter (brightness boost):\n", res)


Add filter (brightness boost):
 [[105. 160.]
 [155. 220.]]


In [11]:
# Adding a constant (increase brightness uniformly)
x = np.array([[100, 150],
              [140, 200]], dtype=np.float64
)

res = x + 50
print("Add 50 to all pixels (brightness adjustment):\n", res)

Add 50 to all pixels (brightness adjustment):
 [[150. 200.]
 [190. 250.]]


In [13]:
# Element-wise subtraction (e.g., remove background or detect changes from 1 frame to another)
# x could be one frame and y could be another frame
x = np.array([[100, 150],
              [140, 200]], dtype=np.float64
)

y = np.array([[5, 10],
              [15, 20]], dtype=np.float64
)

# res = x - y
res = np.subtract(x, y)
print("Subtract filter (change detection):\n", res)

Subtract filter (change detection):
 [[ 95. 140.]
 [125. 180.]]


In [15]:
# Element-wise multiplication (e.g., applying a weight y or blending mask y to image x)

x = np.array([[100, 150],
              [140, 200]], dtype=np.float64
)

y = np.array([[.5, .10],
              [.15, .20]], dtype=np.float64
)

# res = x * y
res = np.multiply(x, y)
print("Pixel-wise blending (weighted effect):\n", res)

Pixel-wise blending (weighted effect):
 [[50. 15.]
 [21. 40.]]


In [16]:
# Now lets perform element-wise division
x = np.array([[100, 150],
              [130, 20]], dtype=np.float64
)

y = np.array([[.5, .10],
              [.15, .20]], dtype=np.float64
)

res = x / y
# res = np.divide(x, y)
print(res)

[[ 200.         1500.        ]
 [ 866.66666667  100.        ]]


In [17]:
# Elementwise operation: sqrt, power, exp, log, floor, ceil, round

x = np.array([[1,2 , 3],
              [4, 5, 6]], dtype=np.float64
) # 2D array of shape 2X3

square_result = np.sqrt(x)
print("Square:\n", square_result)

Square:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [18]:
x = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.float64
) # 2D array of shape 2X3

power_result = np.power(x, 2)  # Raises each element to the power of 2
print("Power:\n", power_result)

Power:
 [[ 1.  4.  9.]
 [16. 25. 36.]]


In [19]:
x = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.float64
) # 2D array of shape 2X3

exp_result = np.exp(x)  # Computes e^x for each element
print("Exponential:\n", exp_result)

Exponential:
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [20]:
x = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.float64
) # 2D array of shape 2X3

log_result = np.log(x)  # Computes the natural logarithm
print("Natural Logarithm:\n", log_result)

Natural Logarithm:
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [21]:
x = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.float64
) # 2D array of shape 2X3

log10_result = np.log10(x)  # Computes the base-10 logarithm
print("Base-10 Logarithm:\n", log10_result)

Base-10 Logarithm:
 [[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]


In [22]:
x = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.float64
) # 2D array of shape 2X3

floor_result = np.floor(x + 0.5)  # Rounds down
print("Floor:\n", floor_result)

Floor:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [23]:
x = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.float64
) # 2D array of shape 2X3

ceil_result = np.ceil(x + 0.5)    # Rounds up
print("Ceil:\n", ceil_result)

Ceil:
 [[2. 3. 4.]
 [5. 6. 7.]]


In [24]:
x = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.float64
) # 2D array of shape 2X3

round_result = np.round(x + 0.5)   # Rounds to nearest integer
print("Round:\n", round_result)

Round:
 [[2. 2. 4.]
 [4. 6. 6.]]


In [25]:
# A simple application: chaining
# Suppose you have to sqrt all numbers, then multiply by 2 and then add 5 to all elements

x = np.array(
    [[1,2],
     [3,4]
    ], dtype = np.uint16
)


res =  (np.sqrt(x) * 2 ) + 5
print(res)

[[7.        7.8284273]
 [8.464102  9.       ]]


In [27]:
# Lets say you want to raise every number in an array by some number that is in different array
a = np.array([2, 3, 4])
b = np.array([3, 2, 3])

result = np.power(a, b)
print(result)  # Output: [8 9 4] → [2^3, 3^2, 4^1]

[ 8  9 64]


In [28]:
a = np.array([10, 20, 30])
b = np.array([3,  7,   8])

# rem = np.remainder(a, b)
rem = np.mod(a, b)
print(rem)  # Output: [1 6 6]

[1 6 6]


In [29]:
a = np.array([10, 20, 30])
b = np.array([3,   7,   8])

result = np.floor_divide(a, b)
print(result)  # Output: [3 2 3] → [10//3, 20//7, 30//8]

[3 2 3]


In [30]:
# sum

x = np.array([3, 2, 2, 4, -1 ,6]) 

print(np.sum(x)) 

16


In [31]:
# prod(), cumsum(), cumprod(), diff()

# Application:A person 3 outfit_options:  2 shirts, 3 pants, and 4 pairs of shoes.
# Finding all possible combinations of items from different categories.
arr = np.array([2, 3, 4]) 
result = np.prod(arr) # Total combinations = 2 * 3 * 4 = 24
print(result)  # Output: 24 → 2*3*4

24


In [32]:
# Tracking savings growth over time.
arr = np.array([100, 150, 200, 250]) # monthly_savings
result = np.cumsum(arr) # Calculate cumulative monthly savings.
print(result)  

[100 250 450 700]


In [33]:
# Calculate cumulative return on investment where gains compound.
# this is a return: # Example: Yearly return multipliers (e.g., 10% gain → 1.10)
arr = np.array([1.10, 1.05, 0.98, 1.20]) 
result = np.cumprod(arr) # Cumulative compounded return
print(result) 

[1.1     1.155   1.1319  1.35828]


In [34]:
# Use Case: Calculate daily increase in website traffic.
arr = np.array([10, 15, 30, 25, 31]) # i.e. visitors 
result = np.diff(arr) # daily increase
print(result)  

[ 5 15 -5  6]
