In [ ]:
import numpy as np

In [4]:
# create 2D data of shape 12X10 

arr = np.random.randint(1, 10, size=(12,10))
print(arr)

[[7 1 5 4 9 7 6 4 8 4]
 [9 6 3 3 8 2 2 4 4 1]
 [4 7 4 5 1 8 4 9 3 8]
 [4 7 1 9 4 4 9 5 5 8]
 [6 6 8 6 5 5 9 6 5 9]
 [7 4 6 8 7 3 6 5 4 6]
 [3 2 5 4 9 3 1 7 1 5]
 [2 5 7 7 9 1 6 9 2 6]
 [3 1 6 9 9 8 3 9 4 1]
 [4 3 2 1 5 7 5 9 7 8]
 [8 7 3 4 5 7 1 7 7 7]
 [1 3 9 2 3 7 4 4 8 1]]


In [5]:
# Export the arr to CSV file with comma delimiter

np.savetxt("data_raw.csv", arr, delimiter=",")

In [6]:
# Now lets import the above data from CSV file that we just created

data = np.genfromtxt("data_raw.csv", delimiter=",")
print(data)
print(data.dtype)

[[7. 1. 5. 4. 9. 7. 6. 4. 8. 4.]
 [9. 6. 3. 3. 8. 2. 2. 4. 4. 1.]
 [4. 7. 4. 5. 1. 8. 4. 9. 3. 8.]
 [4. 7. 1. 9. 4. 4. 9. 5. 5. 8.]
 [6. 6. 8. 6. 5. 5. 9. 6. 5. 9.]
 [7. 4. 6. 8. 7. 3. 6. 5. 4. 6.]
 [3. 2. 5. 4. 9. 3. 1. 7. 1. 5.]
 [2. 5. 7. 7. 9. 1. 6. 9. 2. 6.]
 [3. 1. 6. 9. 9. 8. 3. 9. 4. 1.]
 [4. 3. 2. 1. 5. 7. 5. 9. 7. 8.]
 [8. 7. 3. 4. 5. 7. 1. 7. 7. 7.]
 [1. 3. 9. 2. 3. 7. 4. 4. 8. 1.]]
float64


In [7]:
# OPTIONAL: Lets convert the above to dtype=np.uint8

data = data.astype(np.uint8) # 0 - 255
print(data)
print(data.dtype)

[[7 1 5 4 9 7 6 4 8 4]
 [9 6 3 3 8 2 2 4 4 1]
 [4 7 4 5 1 8 4 9 3 8]
 [4 7 1 9 4 4 9 5 5 8]
 [6 6 8 6 5 5 9 6 5 9]
 [7 4 6 8 7 3 6 5 4 6]
 [3 2 5 4 9 3 1 7 1 5]
 [2 5 7 7 9 1 6 9 2 6]
 [3 1 6 9 9 8 3 9 4 1]
 [4 3 2 1 5 7 5 9 7 8]
 [8 7 3 4 5 7 1 7 7 7]
 [1 3 9 2 3 7 4 4 8 1]]
uint8
