In [9]:
import numpy as np

In [10]:
# Addition: A is 2x3 matrix, and B is 2X3 matrix

A = np.array([[1, 2, 3],
              [4, 5, 6]]
) 

B = np.array([[5, 7, 9],
              [2, 3, 8]]
) 

result = A + B
print(result)

[[ 6  9 12]
 [ 6  8 14]]


In [11]:
# Subtraction: A is 2x3 matrix, and B is 2X3 matrix

A = np.array([[1, 2, 3],
              [4, 5, 6]]
) 

B = np.array([[5, 7, 9],
              [2, 3, 8]]
) 

result = A - B
print(result)

[[-4 -5 -6]
 [ 2  2 -2]]


In [14]:
# Multiplication e.g.1: A is 2x3 matrix, and B is 3X2 matrix. The product would be 2X2 matrix

A = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2x3 matrix

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])    # 3x2 matrix

# 3 ways to perform Matrix multiplication 
# result = A @ B 
# result = np.matmul(A, B) 
result = np.dot(A, B) # not a good way

print("Matrix multiplication:\n", result)

Matrix multiplication:
 [[ 58  64]
 [139 154]]


In [15]:
# Multiplication e.g.2: A is 3x2 matrix, and B is 2X3 matrix. The product would be 3X3 matrix

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])  # 3x2 matrix

B = np.array([[7, 8, 9],
              [10, 11, 12]])  # 2x3 matrix

# 3 ways to perform Matrix multiplication 
result = A @ B 
# result = np.matmul(A, B) 
# result = np.dot(A, B) # not a good way

print("Matrix multiplication:\n", result)

Matrix multiplication:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [16]:
# Multiplication e.g.3: A is 3x2 matrix, and B is 2X5 matrix. The product would be 3X5 matrix

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])  # 3x2 matrix

B = np.array([[7,  8,  9,  3, 1],
              [10, 11, 12, 2, 1]]
            
            )  # 2x5 matrix

# 3 ways to perform Matrix multiplication 
result = A @ B 
# result = np.matmul(A, B) 
# result = np.dot(A, B) # not a good way

print("Matrix multiplication:\n", result)

Matrix multiplication:
 [[ 27  30  33   7   3]
 [ 61  68  75  17   7]
 [ 95 106 117  27  11]]


In [17]:
# Here we perform dot product between two vectors

v = np.array([7,    8,    9]) # Candidate's scores on 3 subjects
w = np.array([0.1, 0.8, 0.1]) #  Weights for each subject

# Inner product of vectors; both produce same result
print(np.dot(v, w)) # Weighted score calculation using dot product
print(v.dot(w))

8.0
8.0


In [18]:
# Dot product between matrix and vector (order matters): A*x
# If A is (m, n) and x is (n,), then np.dot(A, x) would have shape=(m,)

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])   # 3x2 matrix
x = np.array([7, 8])     # 2-dimensional vector

result = np.dot(A, x)    # shape: (3,)
print(result) 

[23 53 83]
