# Descriptive Statistics:
Variance and Standard Deviation

In [1]:
import numpy as np

In [2]:
data = np.array([2, 5, 7, 5, 6])   

mean = np.mean(data)
var  = np.var(data)
sd   = np.std(data)

print("data:", data)
print("Mean:", mean)
print("Variance:", var)
print("Standard Deviation1:", sd)

data: [2 5 7 5 6]
Mean: 5.0
Variance: 2.8
Standard Deviation1: 1.6733200530681511


In [3]:
# Lets understand variance and standard deviation through a data with different variance
data1 = np.array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])   # no variance
data2 = np.array([4, 3, 5, 6, 7, 3, 5, 6, 4, 5])   # some variance
data3 = np.array([1, 1, 0, 0, 5, 9, 9, 10, 10, 5]) # large variance

var1 = np.var(data1)
sd1 = np.std(data1)
print(data1)
print("Variance1:", var1, "; Standard Deviation1:", sd1, "\n")

var2 = np.var(data2)
sd2 = np.std(data2)
print(data2)
print("Variance2:", var2, "; Standard Deviation2:", sd2, "\n")
 
var3 = np.var(data3)
sd3 = np.std(data3)
print(data3)
print("Variance3:", var3, "; Standard Deviation3:", sd3)

[5 5 5 5 5 5 5 5 5 5]
Variance1: 0.0 ; Standard Deviation1: 0.0 

[4 3 5 6 7 3 5 6 4 5]
Variance2: 1.56 ; Standard Deviation2: 1.2489995996796797 

[ 1  1  0  0  5  9  9 10 10  5]
Variance3: 16.4 ; Standard Deviation3: 4.049691346263317
