In [2]:
import numpy as np

In [6]:
# accessing elements and modifing element
# NOTE: indexing starts with 0

# 1.  Lets access 1D array of shape (4) and modify an element
a = np.array([60, 43, 12, 35])   # Create a rank 1(i.e. 1D) array
print(a)

print(a[0])
print(a[3])

# Change an element of the array
a[0] = 5
print(a)
print("####################")

[60 43 12 35]
60
35
[ 5 43 12 35]
####################


In [11]:
# 2. access 2D array and modify elements
# Use: b[row_index][column_index]
# or   b[row_index, column_index]

# Create a 2D array of shape 2X3
b = np.array([
    [1,2,3],
    [4,5,6]
])    

print(b[0][0]) # row=0, col=0
print(b[0, 0])


print(b[0][1]) # row_idx=0, col_idx=1
print(b[0, 1])

print(b[1][2]) # row_idx=1, col_idx=2
print(b[1, 2])


1
1
2
2
6
6


In [13]:
# lets change an element. There are 2 ways
# b[0][2] = -9
b[0,2]  = -9 
print(b)

[[ 1  2 -9]
 [ 4  5  6]]


In [15]:
# ADVANCED: 3. access 3D array and modify elements
# Use: b[block_index][row_index][column_index]
# or   b[block_index, row_index, column_index]

# lets create a 3D array of shape 2X3X5
b = np.array([
    [  # First block (depth index 0)
        [1, 2, 3, 4, 5],      # row = 0
        [6, 7, 8, 9, 10],     # row = 1
        [11, 12, 13, 14, 15]  # row = 2
    ],
    
    [  # Second block (depth index 1)
        [16, 17, 18, 19, 20], # row = 0
        [21, 22, 23, 24, 25], # row = 1
        [26, 27, 28, 29, 30]  # row = 2
    ]
])

print(b[0][2][0])  # depth_idx=0, row_idx=2, col_idx=0
print(b[0, 2, 0])  # depth_idx=0, row_idx=2, col_idx=0 

print(b[1, 2, 0])  # depth_idx=1, row_idx=2, col_idx=0
print(b[1, 0, 3])  # depth_idx=1, row_idx=0, col_idx=3

b[1, 0, 3] = -9
print(b)


11
11
26
19
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 -9 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [16]:
np.random.seed(42) # Set the seed for reproducibility

# Lets create a 4X8 array with random numbers between 0 to 10
a = np.random.randint(0, 10, size=(4, 8))
print(a)

[[6 3 7 4 6 9 2 6]
 [7 4 3 7 7 2 5 4]
 [1 7 5 1 4 0 9 5]
 [8 0 9 2 6 3 8 2]]


In [17]:
# [start_idx:stop_idx:step]

# I want a subarray consisting of the first 2 rows(i.e. rows 0 and 1)
# and columns 1 and 2. I use slicing
b = a[0:2, 1:3]
print(b)

[[3 7]
 [4 3]]


In [18]:
# I want a subarray consisting of row_idx from 1 to 3 and
# and column_idx from 3 to and 7. I use slicing
b = a[1:4, 3:8]
print(b)
print("##########################")


[[7 7 2 5 4]
 [1 4 0 9 5]
 [2 6 3 8 2]]
##########################


In [19]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print("Before:\n", a)   
b[0, 0] = -9     # b[0, 0] is the same piece of data as a[1, 3]
print("After:\n", a)

Before:
 [[6 3 7 4 6 9 2 6]
 [7 4 3 7 7 2 5 4]
 [1 7 5 1 4 0 9 5]
 [8 0 9 2 6 3 8 2]]
After:
 [[ 6  3  7  4  6  9  2  6]
 [ 7  4  3 -9  7  2  5  4]
 [ 1  7  5  1  4  0  9  5]
 [ 8  0  9  2  6  3  8  2]]
