# Hands-on: Simple RNN in TensorFlow/Keras

In [62]:
# 1) Simple sentences
sentences = [
    "i love going to movies",
    "i love going to park",
    "i love machine learning",
    "i love going to planet Mars"
    "ai is future",
    "machine learning is powerful",
    "love going to Mars"
]


In [44]:
# 2)
# sentences = [
#     "i love eating apples",
#     "i love eating food",
#     "i love machine theory",
#     "i love eating spicy vegetables",
#     "i love deep learning",
#     "i love machine learning",
#     "i enjoy learning ai",
#     "i enjoy machine learning",
#     "i enjoy deep learning",
    
#     "ai is the future",
#     "machine learning is powerful",
#     "deep learning is amazing",
#     "ai is transforming industries",
#     "machine learning is evolving",
#     "deep learning is growing fast",
    
#     "ai can solve problems",
#     "machine learning can predict outcomes",
#     "deep learning can recognize images",
#     "ai can automate tasks",
#     "machine learning can find patterns",
#     "deep learning can process data",
    
#     "learning ai is fun",
#     "learning machine learning is interesting",
#     "learning deep learning is exciting",
#     "ai learning is important",
#     "machine learning skills are valuable",
#     "deep learning skills are in demand",
    
#     "i study ai daily",
#     "i study machine learning daily",
#     "i study deep learning daily",
#     "i practice ai projects",
#     "i practice machine learning models",
#     "i practice deep learning models",
    
#     "ai will change the world",
#     "machine learning will improve systems",
#     "deep learning will enhance applications"
# ]


# Step 1: Tokenization

In [63]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[2, 1, 3, 4, 8], [2, 1, 3, 4, 9], [2, 1, 5, 6], [2, 1, 3, 4, 10, 11, 7, 12], [5, 6, 7, 13], [1, 3, 4, 14]]


In [64]:
print("\nWord to Index Mapping:\n")
print(tokenizer.word_index)


Word to Index Mapping:

{'love': 1, 'i': 2, 'going': 3, 'to': 4, 'machine': 5, 'learning': 6, 'is': 7, 'movies': 8, 'park': 9, 'planet': 10, 'marsai': 11, 'future': 12, 'powerful': 13, 'mars': 14}


# Step 2: Create Input-Output Pairs

In [65]:
input_sequences = []

for seq in sequences:
    for i in range(1, len(seq)):
        input_sequences.append(seq[:i+1])

print("input sequences:", input_sequences)
print("------------------------------------")
for s in input_sequences:
    print(s)


[[2, 1], [2, 1, 3], [2, 1, 3, 4], [2, 1, 3, 4, 8], [2, 1], [2, 1, 3], [2, 1, 3, 4], [2, 1, 3, 4, 9], [2, 1], [2, 1, 5], [2, 1, 5, 6], [2, 1], [2, 1, 3], [2, 1, 3, 4], [2, 1, 3, 4, 10], [2, 1, 3, 4, 10, 11], [2, 1, 3, 4, 10, 11, 7], [2, 1, 3, 4, 10, 11, 7, 12], [5, 6], [5, 6, 7], [5, 6, 7, 13], [1, 3], [1, 3, 4], [1, 3, 4, 14]]


In [ ]:
[2, 1, 3, 4, 8]
i love going to movies

# Step 3: Padding

In [66]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = max([len(seq) for seq in input_sequences])

input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')

print(input_sequences)

[[ 0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  2  1  3]
 [ 0  0  0  0  2  1  3  4]
 [ 0  0  0  2  1  3  4  8]
 [ 0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  2  1  3]
 [ 0  0  0  0  2  1  3  4]
 [ 0  0  0  2  1  3  4  9]
 [ 0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  2  1  5]
 [ 0  0  0  0  2  1  5  6]
 [ 0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  2  1  3]
 [ 0  0  0  0  2  1  3  4]
 [ 0  0  0  2  1  3  4 10]
 [ 0  0  2  1  3  4 10 11]
 [ 0  2  1  3  4 10 11  7]
 [ 2  1  3  4 10 11  7 12]
 [ 0  0  0  0  0  0  5  6]
 [ 0  0  0  0  0  5  6  7]
 [ 0  0  0  0  5  6  7 13]
 [ 0  0  0  0  0  0  1  3]
 [ 0  0  0  0  0  1  3  4]
 [ 0  0  0  0  1  3  4 14]]


# Step 4: Split X and y

In [67]:
import numpy as np

X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [68]:
X

array([[ 0,  0,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  0,  0,  2,  1],
       [ 0,  0,  0,  0,  2,  1,  3],
       [ 0,  0,  0,  2,  1,  3,  4],
       [ 0,  0,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  0,  0,  2,  1],
       [ 0,  0,  0,  0,  2,  1,  3],
       [ 0,  0,  0,  2,  1,  3,  4],
       [ 0,  0,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  0,  0,  2,  1],
       [ 0,  0,  0,  0,  2,  1,  5],
       [ 0,  0,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  0,  0,  2,  1],
       [ 0,  0,  0,  0,  2,  1,  3],
       [ 0,  0,  0,  2,  1,  3,  4],
       [ 0,  0,  2,  1,  3,  4, 10],
       [ 0,  2,  1,  3,  4, 10, 11],
       [ 2,  1,  3,  4, 10, 11,  7],
       [ 0,  0,  0,  0,  0,  0,  5],
       [ 0,  0,  0,  0,  0,  5,  6],
       [ 0,  0,  0,  0,  5,  6,  7],
       [ 0,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  1,  3],
       [ 0,  0,  0,  0,  1,  3,  4]])

In [69]:
y

array([ 1,  3,  4,  8,  1,  3,  4,  9,  1,  5,  6,  1,  3,  4, 10, 11,  7,
       12,  6,  7, 13,  3,  4, 14])

# Step 5: Build RNN Model

In [70]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

vocab_size = len(tokenizer.word_index) + 1
embedding =  Embedding(vocab_size,
              # embedding dimension. I want you to represent each word with vector of 10 numbers
              10, 
              input_length=max_len-1
)
print("embedding (Before):", embedding.get_weights())

model = Sequential([
    embedding,
    SimpleRNN(50), # 50 = number of neurons (hidden units)
    Dense(vocab_size, activation='softmax')
])

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy']
)

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 7, 10)             150       
                                                                 
 simple_rnn_4 (SimpleRNN)    (None, 50)                3050      
                                                                 
 dense_4 (Dense)             (None, 15)                765       
                                                                 
Total params: 3965 (15.49 KB)
Trainable params: 3965 (15.49 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Step 6: Train Model

In [71]:
model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 2.6938 - accuracy: 0.1667
Epoch 2/100
1/1 [==============================] - 0s 12ms/step - loss: 2.6743 - accuracy: 0.1667
Epoch 3/100
1/1 [==============================] - 0s 9ms/step - loss: 2.6542 - accuracy: 0.1667
Epoch 4/100
1/1 [==============================] - 0s 9ms/step - loss: 2.6329 - accuracy: 0.1667
Epoch 5/100
1/1 [==============================] - 0s 11ms/step - loss: 2.6101 - accuracy: 0.1667
Epoch 6/100
1/1 [==============================] - 0s 10ms/step - loss: 2.5857 - accuracy: 0.1667
Epoch 7/100
1/1 [==============================] - 0s 17ms/step - loss: 2.5597 - accuracy: 0.1667
Epoch 8/100
1/1 [==============================] - 0s 14ms/step - loss: 2.5325 - accuracy: 0.1667
Epoch 9/100
1/1 [==============================] - 0s 10ms/step - loss: 2.5045 - accuracy: 0.1667
Epoch 10/100
1/1 [==============================] - 0s 11ms/step - loss: 2.4766 - accuracy: 0.1667
Epoch 11/100
1/1 [=====

In [ ]:
# Lets look at the embedding 

embedding_weights = model.layers[0].get_weights()[0]
print("embedding_weights:\n", embedding_weights)
print("-------------------------------")

word_index = tokenizer.word_index

word = "love"
index = word_index[word]

print(f"{word} -> {embedding_weights[index]}")

# Step 7: Prediction Function

In [72]:
import numpy as np

def predict_next_word(text):
    seq = tokenizer.texts_to_sequences([text])[0]
    seq = pad_sequences([seq], maxlen=max_len-1, padding='pre')

    predict_probability = model.predict(seq, verbose=0)[0]
    # print("predict_probability:", predict_probability)

    # (OPTIONAL): print next word and its probability in sorted manner
    index_to_word = {index: word for word, index in tokenizer.word_index.items()}
    sorted_indices = np.argsort(predict_probability)[::-1]
    print("\nWord Probabilities:\n")
    for i in sorted_indices:
       word = index_to_word.get(i, "PAD/UNK")
       prob = predict_probability[i]
       print(f"{word} → {prob:.4f}")   
    # (END OPTIONAL) 
        
    predicted = np.argmax(predict_probability, axis=-1)
    
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            return word


In [74]:
next_word = predict_next_word("i love") 
print("--------------")
print("next_word:", next_word)


Word Probabilities:

going → 0.6375
machine → 0.1058
love → 0.0879
to → 0.0598
learning → 0.0349
powerful → 0.0276
is → 0.0213
mars → 0.0064
PAD/UNK → 0.0042
park → 0.0030
movies → 0.0029
future → 0.0029
marsai → 0.0025
i → 0.0020
planet → 0.0014
--------------
going
